env:
  run_id: 0
  base_config: config.yaml
  use_wandb: False
  debug: False
  resume: False
  wandb_entity: megvii_WideAngle # modify in file
  mode: train # 'train'/'test'/'inference'
  log_dir: output
  seed: 42 # None for random seed
  CKPT_DIR: 'checkpoints' # modify in file
  device: 0
  project: 'BCD' # modify in file

# ==== all the following configs are modified in file ====
DDP: 
  use_ddp: False
  local_ranks: [0, 1]  # [0, 2, 4, 6] ... or ALL

huggingface:
  push_to_hub: False
  hub_model_id: None

model:
  # pretrained_model_name_or_path: 'stabilityai/stable-diffusion-2-inpainting'
  pretrained_model_name_or_path: 'models/sd2inpainting'
  revision: None
  resume_file: ''
  ckpt_path: ''
  prediction_type: 'epsilon' # 'epsilon' / 'sample' / 'v_prediction'
  max_grad_norm: -1 # -1 means no clipping, float value means clipping

lora:
  use_lora: False
  lora_rank: 16 # int
  lora_alpha: 27 # int
  lora_dropout: 0.0 # float
  lora_bias: 'none' # 'none'/'all'/'lora_only'

train:
  batch_size: 2 
  epochs: 25
  val_interval: 20 # epoch 
  val_save_output: True 
  val_save_dir: 'val_output'
  max_steps: None # Set to None to train until the end of the dataset for each epoch
  gradient_accumulation_steps: 1
  mixed_precision: 'no' # 'no'/'fp16'/'bf16'
  enable_xformers: False
  gradient_checkpointing: False # Enable gradient checkpointing to save memory
  allow_tf32: True # Enable TF32 for faster training on Ampere GPUs
  use_8bit_adam: False # Use 8-bit Adam for lower memory usage or to fine-tune the model in 16GB GPUs

lr:
  learning_rate: 0.0001
  scale_lr: False
  lr_scheduler: 'constant' # 'linear'/'cosine'/'cosine_with_restarts'/ 'polynomial'/'constant'/ 'constant_with_warmup'
  lr_warmup_steps: 500 # number of steps for lr warmup
  lr_num_cycles: 1 # number of cycles for cosine_with_restarts
  lr_power: 1.0 # power factor for polynomial lr scheduler

test:
  save_test_img: True
  record_time: False
  test_img_dir: ""

transform:
  resize: False
  change_color: False
  flip: True
  random_crop: True
  crop_size_w: 256
  crop_size_h: 256

data: 
  DATA_ROOT: 'data'
  num_workers: 2
  img_size_w: 256
  img_size_h: 384
  infer_dir: 'data/inference_data'