env:
  run_id: 0
  base_config: config/train_config.yaml
  debug: False
  mode: inference # 'train'/'test'/'inference'
  task: bcd # 'bcd' / 'bcd-inpainting'
  log_dir: output_DSIA # modify in file
  output_dir: checkpoints # modify in file
  seed: 42 # None for random seed
  local_rank: -1 # For distributed training: local_rank
  data: bcd_data # modify in file 'bcd_data' or 'render_data'
  test_save_dir: "" 
  decoupled_attn: False # Use decoupled attention for BCD task
  save_seq: False # Save sequence of diffusion images

huggingface:
  push_to_hub: False
  hub_model_id: None
  hub_token: ""

tracker:
  report_to : 'none' # 'wandb'/'none'
  # Tensorboard
  logging_dir: "logs" # [TensorBoard](https://www.tensorflow.org/tensorboard) log directory. Will default to *output_dir/runs/**CURRENT_DATETIME_HOSTNAME***.
  # Wandb
  wandb_entity: megvii_WideAngle # modify in file
  project: Align # modify in file

model:
  pretrained_model_name_or_path: 'output/train/train-20241223092440/checkpoints/final_model'
  enable_refine_net: False
  clip_name_or_path: 'models/CLIP-ViT-H-14-laion2B-s32B-b79K' # Only for decoupled attention
  use_rnd: False
  num_inference_steps: 30 # for ddim 30 step is enough. for DDPM recommend 200 steps 
  enable_xformers_memory_efficient_attention: True
  enable_model_cpu_offload: False

transform:
  resize: True
  change_color: False
  random_flip: False
  random_crop: False
  center_crop: False
  crop_size_w: 512
  crop_size_h: 384
  crop_by_mask: False

data: 
  DATA_ROOT: 'data'
  num_workers: 2
  img_size_w: 960
  img_size_h: 512
  change_infer_size: True
  infer_w: 960
  infer_h: 512
  infer_dir: 'data/DSIA/test'
  random_mask: False
