env:
  run_id: 0
  base_config: config/train_vae.yaml
  debug: False
  mode: train # 'train'/'test'
  log_dir: output_VAE # modify in file
  output_dir: checkpoints # modify in file
  seed: 42 # None for random seed
  local_rank: -1 # For distributed training: local_rank
  data: render_data # modify in file 'bcd_data' or 'render_data'

huggingface:
  push_to_hub: False
  hub_model_id: None
  hub_token: ""

tracker:
  report_to : 'none' # 'wandb'/'none'
  # Tensorboard
  logging_dir: "logs" # [TensorBoard](https://www.tensorflow.org/tensorboard) log directory. Will default to *output_dir/runs/**CURRENT_DATETIME_HOSTNAME***.
  # Wandb
  wandb_entity: megvii_WideAngle # modify in file
  project: BCD_VAE # modify in file

model:
  pretrained_model_name_or_path: 'checkpoints/vae/4x/render_real_30epoch'
  clip_name_or_path: ""
  use_4x_downsample_vae: True # Use 4x downsampling VAE replacing the default 8x downsampling VAE
  revision: None
  variant: None
  cache_dir: None # The directory where the downloaded models and datasets will be stored.
  resume_from_checkpoint: None # Whether training should be resumed from a previous checkpoint. Use a path saved by 'checkpointing_steps', or `"latest"` to automatically select the last available checkpoint, None for no resuming.
  max_grad_norm: 1.0 # -1 means no clipping, float value means clipping
  
train:
  batch_size: 2
  epochs: 15 # 15 for render. 30 for bcd.
  max_train_steps: None # Total number of training steps to perform. If provided, overrides num_train_epochs.
  gradient_accumulation_steps: 1
  gradient_checkpointing: False # Enable gradient checkpointing to save memory
  input_perturbation: 0 # The scale of input perturbation. Recommended 0.1.
  use_8bit_adam: False # Use 8-bit Adam for lower memory usage or to fine-tune the model in 16GB GPUs
  allow_tf32: True # Enable TF32 for faster training on Ampere GPUs
  mixed_precision: 'no' # 'no'/'fp16'/'bf16'
  checkpointing_steps: 5000 # Save a checkpoint every X steps, These checkpoints are only suitable for resuming training using `--resume_from_checkpoint`.
  checkpoints_total_limit: 10 # Max number of checkpoints to store.
  noise_offset: 0 # The scale of noise offset.
  validation_epochs: 5 # Run validation every X epochs. 
  val_save_output: True 
  val_save_dir: ''

loss:
  use_recon_loss: False
  use_texture_loss: False
  use_fidelity_loss: False
  recon_loss_weight: 1.0
  texture_loss_weight: 0.1
  fidelity_loss_weight: 1.0
  
optim:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1.e-2
  adam_epsilon: 1.e-8

lr:
  learning_rate: 1.e-4
  scale_lr: False
  lr_scheduler: 'constant' # 'linear'/'cosine'/'cosine_with_restarts'/ 'polynomial'/'constant'/ 'constant_with_warmup'
  lr_warmup_steps: 500 # number of steps for lr warmup
  lr_num_cycles: 1 # number of cycles for cosine_with_restarts
  lr_power: 1.0 # power factor for polynomial lr scheduler

transform:
  resize: True
  change_color: False
  random_flip: False
  random_crop: False
  center_crop: False
  crop_size_w: 256
  crop_size_h: 256

data: 
  DATA_ROOT: 'data'
  num_workers: 2
  img_size_w: 512
  img_size_h: 384
  infer_w: 512
  infer_h: 384
  infer_dir: 'data/inference_data'